# Generated by Django 5.0.3 on 2024-04-25 11:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_user', models.BooleanField(default=False)),
                ('is_Customer', models.BooleanField(default=False)),
                ('is_Manufacturers', models.BooleanField(default=False)),
                ('is_Sales', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('Buyer_Name', models.CharField(max_length=100, null=True)),
                ('Date_of_supply', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('Product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_Id', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=255)),
                ('Booking_status', models.CharField(choices=[('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Delivery', 'Delivery')], default='Processing', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_TeamClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sales_Team_ID', models.CharField(max_length=100)),
                ('Sales_Representative_Name', models.CharField(max_length=100)),
                ('Sales_Representative_Email', models.EmailField(max_length=100)),
                ('Sales_Representative_Phone', models.CharField(max_length=10)),
                ('Sales_Region', models.CharField(max_length=100)),
                ('Sales_Manager', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShutterDtls',
            fields=[
                ('product_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_Name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Wood', 'Wood'), ('PVC', 'PVC'), ('Steel', 'Steel')], max_length=100)),
                ('Material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('quantity_Available', models.CharField(max_length=50)),
                ('Manufacturer_Id', models.CharField(max_length=20)),
                ('supplier_id', models.CharField(max_length=20)),
                ('images', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='feedBack',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='UserFeedBack', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Date', models.DateField(auto_now=True)),
                ('feedBack', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturersDtlClass',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manufact', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Manufacturer_ID', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numbers are allowed')])),
                ('Manufacturer_Name', models.CharField(max_length=50)),
                ('Contact_Person', models.CharField(max_length=50)),
                ('Contact_Email', models.EmailField(max_length=50)),
                ('Contact_Phone', models.CharField(max_length=50)),
                ('Company_Address', models.CharField(max_length=50)),
                ('Company_Website', models.CharField(max_length=50)),
                ('Profile_Description', models.CharField(max_length=50)),
            ],
        ),
    ]
